# Generated by Django 3.2 on 2023-01-22 04:22

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.IntegerField(choices=[(0, 'Active'), (1, 'Inactive'), (2, 'Canceled')], default=0)),
                ('date_created', models.DateField(default=datetime.date.today, null=True)),
                ('date_modified', models.DateField(auto_now=True)),
                ('user_creator', models.CharField(max_length=30)),
                ('user_modifier', models.CharField(max_length=30)),
                ('last_action', models.IntegerField(choices=[(0, 'Create'), (1, 'Uptade'), (2, 'Delete')], default=0)),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=1000)),
                ('level', models.SmallIntegerField()),
                ('group_image', models.ImageField(default='groups/img/default-group-image.jpg', upload_to='groups/img/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'gif', 'jpg', 'webp', 'jpeg'])])),
                ('group_leader', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='user.profile')),
                ('members', models.ManyToManyField(related_name='members', to='user.Profile')),
                ('principal_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='organization.group')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.IntegerField(choices=[(0, 'Active'), (1, 'Inactive'), (2, 'Canceled')], default=0)),
                ('date_created', models.DateField(default=datetime.date.today, null=True)),
                ('date_modified', models.DateField(auto_now=True)),
                ('user_creator', models.CharField(max_length=30)),
                ('user_modifier', models.CharField(max_length=30)),
                ('last_action', models.IntegerField(choices=[(0, 'Create'), (1, 'Uptade'), (2, 'Delete')], default=0)),
                ('name', models.CharField(max_length=50)),
                ('route', models.FileField(upload_to='resources/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'gif', 'jpg', 'webp', 'jpeg', 'pdf'])])),
                ('groups', models.ManyToManyField(to='organization.Group')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
