# Generated by Django 3.2 on 2023-01-22 18:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='date_created',
            field=models.DateTimeField(default=datetime.date.today, null=True),
        ),
        migrations.AlterField(
            model_name='resource',
            name='date_created',
            field=models.DateTimeField(default=datetime.date.today, null=True),
        ),
    ]
