# Generated by Django 3.2 on 2023-01-04 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_auto_20221218_1801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='route',
            field=models.FileField(upload_to=''),
        ),
    ]
