# Generated by Django 3.2 on 2023-01-21 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0004_auto_20230115_2246'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='group_image',
            field=models.ImageField(default='default-group-image.jpg', upload_to='groups/img/'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='route',
            field=models.FileField(upload_to='resources/'),
        ),
    ]
