# Generated by Django 3.2 on 2023-01-20 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0005_auto_20230120_1231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='route',
            field=models.FileField(default='default.png', upload_to='images'),
        ),
    ]
