# Generated by Django 3.2 on 2023-01-21 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0005_auto_20230121_1556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='group_image',
            field=models.ImageField(default='groups/img/default-group-image.jpg', upload_to='groups/img/'),
        ),
    ]
