# Generated by Django 3.2 on 2023-01-20 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0006_alter_image_route'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='img_file',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='file_group', to='organization.image'),
            preserve_default=False,
        ),
    ]
