# Generated by Django 3.2 on 2022-12-02 06:33

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organization', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.IntegerField(choices=[(0, 'Active'), (1, 'Inactive'), (2, 'Canceled')], default=0)),
                ('date_created', models.DateField(default=datetime.date.today, null=True)),
                ('date_modified', models.DateField(auto_now=True)),
                ('user_creator', models.CharField(max_length=30)),
                ('user_modifier', models.CharField(max_length=30)),
                ('last_action', models.IntegerField(choices=[(0, 'Create'), (1, 'Uptade'), (2, 'Delete')], default=0)),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=300)),
                ('type', models.CharField(choices=[('A', 'Admision'), ('B', 'Reunion'), ('C', 'Conferencia')], default='B', max_length=1)),
                ('date_start', models.DateTimeField()),
                ('date_end', models.DateTimeField()),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='organization.group')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='organization.resource')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.IntegerField(choices=[(0, 'Active'), (1, 'Inactive'), (2, 'Canceled')], default=0)),
                ('date_created', models.DateField(default=datetime.date.today, null=True)),
                ('date_modified', models.DateField(auto_now=True)),
                ('user_creator', models.CharField(max_length=30)),
                ('user_modifier', models.CharField(max_length=30)),
                ('last_action', models.IntegerField(choices=[(0, 'Create'), (1, 'Uptade'), (2, 'Delete')], default=0)),
                ('interested_record', models.BooleanField(default=True)),
                ('confirmed_record', models.BooleanField(default=False)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='event.event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='user.profile')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.IntegerField(choices=[(0, 'Active'), (1, 'Inactive'), (2, 'Canceled')], default=0)),
                ('date_created', models.DateField(default=datetime.date.today, null=True)),
                ('date_modified', models.DateField(auto_now=True)),
                ('user_creator', models.CharField(max_length=30)),
                ('user_modifier', models.CharField(max_length=30)),
                ('last_action', models.IntegerField(choices=[(0, 'Create'), (1, 'Uptade'), (2, 'Delete')], default=0)),
                ('content', models.CharField(max_length=80)),
                ('level', models.SmallIntegerField()),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='event.event')),
                ('principal_comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='event.comment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='user.profile')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
