# Generated by Django 3.2 on 2023-01-22 18:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_event_user_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='date_created',
            field=models.DateTimeField(default=datetime.date.today, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='date_created',
            field=models.DateTimeField(default=datetime.date.today, null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='date_created',
            field=models.DateTimeField(default=datetime.date.today, null=True),
        ),
    ]
