# Generated by Django 3.2 on 2023-01-20 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0007_group_img_file'),
        ('event', '0004_remove_event_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='img_file',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='file_event', to='organization.image'),
            preserve_default=False,
        ),
    ]
