# Generated by Django 3.2 on 2023-01-22 18:59

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='card_image',
            field=models.ImageField(default='profile/document/img/default-card-image.png', upload_to='profile/document/img/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'gif', 'jpg', 'webp', 'jpeg'])]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='date_created',
            field=models.DateTimeField(default=datetime.date.today, null=True),
        ),
    ]
