# Generated by Django 3.2 on 2023-01-20 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_profile_card_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='card_id_resource',
        ),
    ]
