# Generated by Django 3.2 on 2023-01-20 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0007_group_img_file'),
        ('user', '0003_remove_profile_card_id_resource'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='card_id_file',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='file_id', to='organization.image'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='img_file',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='file_avatar', to='organization.image'),
            preserve_default=False,
        ),
    ]
